# Generated by Django 3.0.7 on 2020-07-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200710_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='level',
            field=models.CharField(choices=[('critical', 'critical'), ('debug', 'debug'), ('error', 'error'), ('warning', 'warning'), ('information', 'info')], max_length=20),
        ),
    ]
